let S=JSON.parse(localStorage.getItem('fw')||'null')||{assets:{tractor:[],equipment:[],land:[]},work:[]},V=new Date();V.setDate(1);
const $=x=>document.querySelector(x),save=()=>{localStorage.setItem('fw',JSON.stringify(S));render()},esc=x=>(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),day=d=>d.toISOString().slice(0,10),fmt=x=>new Date(x+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
function render(){calendar();sections()}
function calendar(){let y=V.getFullYear(),m=V.getMonth(),first=new Date(y,m,1),n=new Date(y,m+1,0).getDate(),h='';$('#title').textContent=V.toLocaleDateString(undefined,{month:'long',year:'numeric'});for(let i=0;i<first.getDay();i++)h+='<div class="day"></div>';for(let d=1;d<=n;d++){let k=day(new Date(y,m,d)),ws=S.work.filter(w=>w.start<=k&&w.end>=k);h+=`<div class="day ${k==day(new Date())?'today':''}"><span>${d}</span>${ws.map(w=>`<div class="ev ${w.done?'done':''}" onclick="detail('${w.id}')">${esc(w.description)}</div>`).join('')}</div>`}$('#cal').innerHTML=h}
function sections(){let out='';for(let t of ['tractor','equipment','land']){let title=t[0].toUpperCase()+t.slice(1),a=S.assets[t];out+=`<section class="sec"><div class="sh"><h2>${title}</h2><button class="sp" onclick="asset('${t}')">＋</button></div>${a.length?a.map(x=>{let w=S.work.filter(z=>z.assetType==t&&z.assetId==x.id);return `<div class="asset">${esc(x.name)}${w.length?w.map(q=>`<div class="work"><button onclick="complete('${q.id}')">${q.done?'☑':'☐'}</button> <span onclick="detail('${q.id}')">${esc(q.description)} <small>${fmt(q.start)}${q.end!=q.start?' – '+fmt(q.end):''}</small></span></div>`).join(''):'<div class="muted">No work recorded yet.</div>'}</div>`}).join(''):'<div class="muted">None added yet.</div>'}</section>`}$('#sections').innerHTML=out}
function modal(t,b){$('#mt').textContent=t;$('#mb').innerHTML=b;$('#modal').classList.remove('hidden')}function closeM(){$('#modal').classList.add('hidden')}
$('#prev').onclick=()=>{V.setMonth(V.getMonth()-1);calendar()};$('#next').onclick=()=>{V.setMonth(V.getMonth()+1);calendar()};
$('#add').onclick=()=>{modal('Add Work',`<label>Type</label><select id="type" onchange="fields()"><option value="calendar">Calendar</option><option value="tractor">Tractor</option><option value="equipment">Equipment</option><option value="land">Land</option></select><div id="fields"></div>`);fields()};
function fields(){let t=$('#type').value,a=S.assets[t]||[],sel=t!='calendar'?`<label>${t}</label><select id="asset">${a.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`:'';$('#fields').innerHTML=sel+`<label>Description</label><input id="desc" placeholder="What needs to be done?"><div class="grid"><div><label>Beginning date</label><input id="start" type="date" value="${day(new Date())}"></div><div><label>End date</label><input id="end" type="date" value="${day(new Date())}"></div></div><label>Time (optional)</label><input id="time" type="time"><label>Additional notes (optional)</label><textarea id="notes"></textarea><label>Photos (optional)</label><input id="pics" type="file" accept="image/*" multiple capture="environment"><div class="actions"><button class="secondary" onclick="closeM()">Cancel</button><button class="primary" onclick="addWork()">Save Work</button></div>`}
async function imgs(fs){let a=[];for(let f of fs){a.push(await new Promise(r=>{let q=new FileReader();q.onload=()=>r({name:f.name,data:q.result});q.readAsDataURL(f)}))}return a}
async function addWork(){let d=$('#desc').value.trim(),s=$('#start').value,e=$('#end').value;if(!d||!s||!e)return alert('Description, beginning date and end date are required.');if(e<s)return alert('End date cannot be before beginning date.');let t=$('#type').value;S.work.push({id:crypto.randomUUID(),description:d,start:s,end:e,time:$('#time').value,notes:$('#notes').value,assetType:t=='calendar'?null:t,assetId:t=='calendar'?null:$('#asset')?.value,photos:await imgs($('#pics').files),done:false});save();closeM()}
function asset(t){modal('Add '+t,`<label>Name / description</label><input id="an" placeholder="${t=='tractor'?'4020':t=='equipment'?'Planter':'80 acres north field'}"><div class="actions"><button class="secondary" onclick="closeM()">Cancel</button><button class="primary" onclick="addAsset('${t}')">Save</button></div>`)}function addAsset(t){let n=$('#an').value.trim();if(!n)return;S.assets[t].push({id:crypto.randomUUID(),name:n});save();closeM()}
function detail(id){let w=S.work.find(x=>x.id==id);if(!w)return;modal(w.description,`<p><b>Dates:</b> ${fmt(w.start)}${w.end!=w.start?' – '+fmt(w.end):''}${w.time?' • '+w.time:''}</p>${w.notes?`<p><b>Notes:</b> ${esc(w.notes)}</p>`:''}${w.done?`<p><b>Completed:</b> ${fmt(w.completedDate)}${w.completedNotes?' — '+esc(w.completedNotes):''}</p>`:''}${w.photos?.length?'<div class="photos">'+w.photos.map(p=>`<img src="${p.data}">`).join('')+'</div>':''}<div class="actions">${!w.done?`<button class="primary" onclick="complete('${id}')">✓ Mark Complete</button>`:''}<button class="secondary" onclick="closeM()">Close</button></div>`)}
function complete(id){let w=S.work.find(x=>x.id==id);modal('Complete Work',`<label>When was it done?</label><input id="cd" type="date" value="${day(new Date())}"><label>Completion notes (optional)</label><textarea id="cn"></textarea><label>Photos (optional)</label><input id="cp" type="file" accept="image/*" multiple capture="environment"><div class="actions"><button class="secondary" onclick="closeM()">Cancel</button><button class="primary" onclick="finish('${id}')">Save Completion</button></div>`)}
async function finish(id){let w=S.work.find(x=>x.id==id);w.done=true;w.completedDate=$('#cd').value;w.completedNotes=$('#cn').value;w.photos=[...(w.photos||[]),...(await imgs($('#cp').files))];save();closeM()}
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});